    name: Create Release on Main Merge

    on:
      push:
        branches:
          - main
    jobs:
      release:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4

          # Example: Generate a new version tag (e.g., using a script or another action)
          # - name: Get next version
          #   id: get_version
          #   run: |
          #     # Logic to determine the next version (e.g., based on commit messages, last tag)
          #     echo "VERSION=v1.0.0" >> $GITHUB_OUTPUT

          - name: Create Release
            uses: actions/create-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: ${{ steps.get_version.outputs.VERSION }} # Use the generated version
              release_name: Release ${{ steps.get_version.outputs.VERSION }}
              body: |
                Automated release generated after merge to main.
                See changes in ${{ github.event.compare }}
              draft: false
              prerelease: false
