    name: Maven CI

    on: [push, pull_request]

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4 # Checkout the repository code
        - name: Set up JDK 17 # Or your desired Java version
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: maven

        - name: Build and Test with Maven
          run: mvn -B test # -B for batch mode (non-interactive)
